### ISSUE TITLE
header Rendering: Theme or .css??

### ISSUE THREAD

**Issue by lwb52** [santiyounger/Reverie-Obsidian-Theme#1]
perhaps it’s the theme, but maybe it’s another plugin’s impact on the .css, or the renderer Obsidian uses (I understand there’s an update on the way)—nonetheless, bullet marks do not render as expected, which is (something) like:
…•
……◦
………☐
instead, they appear more ”plain&boring" as
…•
……•
………-
this unexpected behavior is similar to Zettler (which does not truly ”render” as far as I can tell)—in Joplin bullets do render as expected.

then, in one vault using Reverie, Headings 1 2 & 3 render as prepended with large bullets AND INDENTATION:
◉ and [?undisplayable?] and ✸
(then repeated for Headings 4 5 & 6)
(expected (no) bullets for headings, and maybe no indentation…)
however, in another vault using this theme, the rendering of headers /does/ have no-bullet & no-indentation…

**Comment by santiyounger** [comment]
Hey thanks for using the Theme,


Regarding the symbols  ✸ ◉ that is on purpose, it's a style taken from another application that some of us are fans of
You can learn more about it here:
https://github.com/santiyounger/Org-sidian-Bullets

That was a project I integrated with Obsidian for anyone to use, temporarily I added it to "Reverie" as a built in feature, but then decided to remove it since not everyone would know what it is.

What happened is you downloaded / updated Reverie while this feature was enabled, if you install the theme again it should be gone.

Communty Themes > Reverie > Use 

this will override the last theme and fix this, if you have additional code you added, checkout the forum or the help vault for css snippets which is a simple way to add customized code to obsidian without having to add things to the theme you are in.

---

Regarding the first part you mentioned on these symbols for bullet lists
…•
……◦
………☐

I do not think that is related to Reverie, but feel free to share here the following:
 - take a screenshot
 - additional code you might have copied into obsidian.css (if applicable) 
 - list of the plugins you are currently using.
  Make sure to update plugins in  Settings> Third-party plugins > Current plugins > Check for updates, scroll to see update bottons on specific plugins.
 
 
 Thanks!

**Comment by santiyounger** [comment]
let me know if this wasn't solved, I'll close this issue for now
